export const products = [
  {
    id: 1,
    name: "Oversize тениска",
    price: 79.99,
    category: "Дамски",
    image: "/products/product1.jpg",
    description: "Памучна oversize тениска.",
    sizes: ["S", "M", "L"],
    colors: ["Бяло", "Черно"],
    isNew: true,
  },
  {
    id: 2,
    name: "Черно яке",
    price: 189.99,
    category: "Мъжки",
    image: "/products/product2.jpg",
    description: "Модерно градско яке.",
    sizes: ["M", "L", "XL"],
    colors: ["Черно"],
    isNew: false,
  },
  {
    id: 3,
    name: "Дънки",
    price: 119.99,
    category: "Мъжки",
    image: "/products/product3.jpg",
    description: "Slim Fit дънки.",
    sizes: ["30", "32", "34"],
    colors: ["Синьо"],
    isNew: true,
  },
  {
    id: 4,
    name: "Худи",
    price: 99.99,
    category: "Дамски",
    image: "/products/product4.jpg",
    description: "Премиум памучно худи.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Сиво", "Черно"],
    isNew: false,
  },
  {
    id: 5,
    name: "Кожена чанта",
    price: 149.99,
    category: "Аксесоари",
    image: "/products/product5.jpg",
    description: "Елегантна кожена чанта.",
    sizes: [],
    colors: ["Черно", "Кафяво"],
    isNew: true,
  },
  {
    id: 6,
    name: "Кожен колан",
    price: 49.99,
    category: "Аксесоари",
    image: "/products/product6.jpg",
    description: "Класически кожен колан.",
    sizes: ["90", "100", "110"],
    colors: ["Черно", "Кафяво"],
    isNew: false,
  },
];